#include <iostream>
#include <vector>

using namespace std;

// generated by copilot, check it later.
class Hamming {
public:
    static vector<int> encode(vector<int> message) {
        vector<int> result;
        int r = 0;
        for (int i = 0; i < message.size(); i++) {
            if (i == (1 << r) - 1) {
                result.push_back(0);
                r++;
            }
            result.push_back(message[i]);
        }
        for (int i = 0; i < result.size(); i++) {
            if (result[i] == 0) {
                int count = 0;
                for (int j = i + 1; j < result.size(); j++) {
                    if (result[j] == 1) {
                        count++;
                    }
                    if (count == i + 1) {
                        result[i] = count % 2;
                        break;
                    }
                }
            }
        }
        return result;
    }
};
